version: '3.8'
name: wire-scout

services:
  mongo:
    image: mongo:8
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wire-scout
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/wire-scout --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://user:password@mongo:27017/
      MONGO_DATABASE: wire-scout
    depends_on:
      mongo:
        condition: service_healthy

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m crawler.main
    environment:
      MONGO_URI: mongodb://user:password@mongo:27017/
      MONGO_DATABASE: wire-scout
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
