name: Github CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install
      - name: Install Python dependencies
        run: make dependencies
      - name: Lint with pylint
        run: |
          make lint

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: make dependencies
      - name: Verify security vulnerabilities
        run: make check

  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: make dependencies
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '8.0'
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: wire-scout
      - name: Unit test
        run: make unit
        env:
          LOG_LEVEL: ERROR
          MONGO_URI: mongodb://admin:admin@localhost:27017
          MONGO_DATABASE: wire-scout

      - name: Report Coverage
        run: uv run coverage lcov
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.lcov
